//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareSystemOrders.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftwareSystemOrders.Resources.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention!.
        /// </summary>
        internal static string AttentionMessage {
            get {
                return ResourceManager.GetString("AttentionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel order.
        /// </summary>
        internal static string CancelOrder {
            get {
                return ResourceManager.GetString("CancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You need to restart the application to apply changes.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear.
        /// </summary>
        internal static string ClearOrdersBtn {
            get {
                return ResourceManager.GetString("ClearOrdersBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear the entire order cache.
        /// </summary>
        internal static string ClearOrdersText {
            get {
                return ResourceManager.GetString("ClearOrdersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click!.
        /// </summary>
        internal static string ClickText {
            get {
                return ResourceManager.GetString("ClickText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        internal static string CompletedOrderPageStatus {
            get {
                return ResourceManager.GetString("CompletedOrderPageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Completed orders.
        /// </summary>
        internal static string CompletedOrderPageTitle {
            get {
                return ResourceManager.GetString("CompletedOrderPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm order.
        /// </summary>
        internal static string ConfirmOrder {
            get {
                return ResourceManager.GetString("ConfirmOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        internal static string CreateBtn {
            get {
                return ResourceManager.GetString("CreateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        internal static string CreateOrderPagePlaceholderEmail {
            get {
                return ResourceManager.GetString("CreateOrderPagePlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string CreateOrderPagePlaceholderName {
            get {
                return ResourceManager.GetString("CreateOrderPagePlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone.
        /// </summary>
        internal static string CreateOrderPagePlaceholderPhone {
            get {
                return ResourceManager.GetString("CreateOrderPagePlaceholderPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create an order.
        /// </summary>
        internal static string CreateOrderPageTitle {
            get {
                return ResourceManager.GetString("CreateOrderPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UAH.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer email:.
        /// </summary>
        internal static string CustomerEmail {
            get {
                return ResourceManager.GetString("CustomerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect email format..
        /// </summary>
        internal static string CustomerEmailError {
            get {
                return ResourceManager.GetString("CustomerEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer ID:.
        /// </summary>
        internal static string CustomerID {
            get {
                return ResourceManager.GetString("CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer information.
        /// </summary>
        internal static string CustomerInformationTitle {
            get {
                return ResourceManager.GetString("CustomerInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer&apos;s name:.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The name cannot be empty..
        /// </summary>
        internal static string CustomerNameError {
            get {
                return ResourceManager.GetString("CustomerNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The phone number is too short..
        /// </summary>
        internal static string CustomerPhoneError {
            get {
                return ResourceManager.GetString("CustomerPhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer phone number:.
        /// </summary>
        internal static string CustomerPhoneNumber {
            get {
                return ResourceManager.GetString("CustomerPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of order:.
        /// </summary>
        internal static string DateOfOrder {
            get {
                return ResourceManager.GetString("DateOfOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на More information.
        /// </summary>
        internal static string DetailedInformation {
            get {
                return ResourceManager.GetString("DetailedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link to my GitHub profile:.
        /// </summary>
        internal static string GitHubProfileText {
            get {
                return ResourceManager.GetString("GitHubProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the language:.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name of product:.
        /// </summary>
        internal static string NameOfProduct {
            get {
                return ResourceManager.GetString("NameOfProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The order has been canceled.
        /// </summary>
        internal static string OrderCanceled {
            get {
                return ResourceManager.GetString("OrderCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The order is confirmed.
        /// </summary>
        internal static string OrderConfirmed {
            get {
                return ResourceManager.GetString("OrderConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order ID:.
        /// </summary>
        internal static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order information.
        /// </summary>
        internal static string OrderInformationTitle {
            get {
                return ResourceManager.GetString("OrderInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order status:.
        /// </summary>
        internal static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Canceled.
        /// </summary>
        internal static string OrderStatus_Canceled {
            get {
                return ResourceManager.GetString("OrderStatus_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delivered.
        /// </summary>
        internal static string OrderStatus_Delivered {
            get {
                return ResourceManager.GetString("OrderStatus_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pending.
        /// </summary>
        internal static string OrderStatus_Pending {
            get {
                return ResourceManager.GetString("OrderStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product.
        /// </summary>
        internal static string PendingOrderPageSubtitleProduct {
            get {
                return ResourceManager.GetString("PendingOrderPageSubtitleProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order processing.
        /// </summary>
        internal static string PendingOrderPageTitle {
            get {
                return ResourceManager.GetString("PendingOrderPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product ID:.
        /// </summary>
        internal static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product price:.
        /// </summary>
        internal static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a product.
        /// </summary>
        internal static string ProductSelection {
            get {
                return ResourceManager.GetString("ProductSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantity:.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the quantity.
        /// </summary>
        internal static string QuantityPlaceholder {
            get {
                return ResourceManager.GetString("QuantityPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string SettingPageTitle {
            get {
                return ResourceManager.GetString("SettingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total price:.
        /// </summary>
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
    }
}
